CREATE TABLE CUSTOMERS (
    CUSTOMER_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY
        (START WITH 1 INCREMENT BY 1),
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL,
    PHONE_NUMBER VARCHAR(30),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT UK_CUSTOMERS_EMAIL UNIQUE (EMAIL)
);

INSERT INTO CUSTOMERS (NAME, EMAIL, PHONE_NUMBER)
VALUES
    ('Kim Minsoo', 'minsoo@example.com', '010-1111-2222'),
    ('Lee Hana', 'hana@example.com', '010-3333-4444');
