CREATE TABLE CUSTOMERS (
    CUSTOMER_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY
        (START WITH 1 INCREMENT BY 1),
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL,
    PHONE_NUMBER VARCHAR(30),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT UK_CUSTOMERS_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE CUSTOMER_STAGING (
    STAGING_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY
        (START WITH 1 INCREMENT BY 1),
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL,
    PHONE_NUMBER VARCHAR(30),
    STATUS VARCHAR(20) NOT NULL DEFAULT 'READY',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT PK_CUSTOMER_STAGING PRIMARY KEY (STAGING_ID)
);

INSERT INTO CUSTOMERS (NAME, EMAIL, PHONE_NUMBER)
VALUES
    ('Kim Minsoo', 'minsoo@example.com', '010-1111-2222'),
    ('Lee Hana', 'hana@example.com', '010-3333-4444');

INSERT INTO CUSTOMER_STAGING (NAME, EMAIL, PHONE_NUMBER, STATUS)
VALUES
    ('Choi Yuna', 'yuna@example.com', '010-5555-1111', 'READY'),
    ('Jung Doyoon', 'doyoon@example.com', '010-5555-2222', 'READY'),
    ('Kim Minsoo Copy', 'minsoo@example.com', '010-5555-3333', 'READY');
