spring.application.name=demo1

spring.datasource.url=${DB2_URL:jdbc:db2://localhost:50000/SAMPLE}
spring.datasource.username=${DB2_USERNAME:db2inst1}
spring.datasource.password=${DB2_PASSWORD:password}
spring.datasource.driver-class-name=com.ibm.db2.jcc.DB2Driver
spring.datasource.hikari.initialization-fail-timeout=-1

mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
